### ISSUE TITLE
What license does this skin have?

### ISSUE THREAD

**Issue by jdlrobson** [tyrm/skin-hive#2]
I'm not sure if the skin is allowed to be used by other people.
Can you clarify with the addition of the field to skin.json ?

https://github.com/wikimedia/Vector/blob/master/skin.json#L12

Thanks in advance! 👍

**Comment by tyrm** [comment]
Nah, this skin is meant for use on our wiki only. it contains lots of hard links to other parts of our site.

**Comment by jdlrobson** [comment]
Understood and that's not a real problem. there are lots of skins like this out there in the wild. 
https://m.mediawiki.org/wiki/Skin:ScratchWikiSkin2 is like this for example. 

I'm just wondering whether it can it be forked/modified/contributed to if people felt inclined :)

**Comment by tyrm** [comment]
oh sure. let me update the license

**Comment by jdlrobson** [comment]
Thank you :)
